### ISSUE TITLE
Build consistently timing out with Julia nightly on Linux

### ISSUE THREAD

**Issue by rdeits** [JuliaPackaging/CMakeWrapper.jl#14]
It looks like this started happening recently:

* https://travis-ci.org/JuliaPackaging/CMakeWrapper.jl/jobs/410847838
* https://travis-ci.org/JuliaPackaging/CMakeWrapper.jl/jobs/410847842

But I'm also seeing the same timeout in downstream dependencies, so whatever is going on is also affecting the most recent release of CMakeWrapper (which predates splitting the package off into CMake.jl).  

* https://travis-ci.org/JuliaRobotics/LCMCore.jl/jobs/410548179

**Comment by tkoolen** [comment]
https://discourse.julialang.org/t/julia-0-7-rc1-5-hangs-on-build-specialfunctions/12794?

**Comment by rdeits** [comment]
Yup, looks very similar. I was just about to comment there :slightly_smiling_face:
